### ISSUE TITLE
04 Matrix --> 07 print matrix in diagonal pattern

### ISSUE THREAD

**Issue by FazeelUsmani** [FazeelUsmani/Amazon-SDE-Test-Series#28]
Given a matrix M of n*n size, the task is to complete the function which prints its elements in diagonal pattern as depicted below.

Example 1:

Input:
N = 3
mat[][] = {{1 2 3},{4 5 6},{7 8 9}}
Output: 1 2 4 7 5 3 6 8 9
Example 2:

Input:
N = 2
mat[][] = {{1 2},{3 4}}
Output: 1 2 3 4
Your Task:
You only need to implement the given function matrixDiagonally() which returns a list containing the matrix diagonally.. Do not read input, instead use the arguments given in the function. Print the elements in Matrix in diagonal pattern.

Expected Time Complexity: O(N*M)
Expected Auxiliary Space: O(1)
Constraints:
0<=N<=20

Note:The Input/Ouput format and Example given are used for system's internal purpose, and should be used by a user for Expected Output only. As it is a function problem, hence a user should not read any input from stdin/console. The task is to complete the function specified, and not to write the full code.

**Comment by KevinKurian7** [comment]
`  
void MatrixDiagonally(int mat[][100], int n) 
{ 
    // Initialize indexes to print the next element
    int i = 0, j = 0; 
  
    //initially the direction is from down to up
    bool Upward = true; 
  
    
    for (int k = 0; k < n * n;) { 
        // If Upward = true then traverse from downward 
        // to upward 
        if (Upward) { 
            for (; i >= 0 && j < n; j++, i--) { 
                cout << mat[i][j] << " "; 
                k++; 
            } 
  
            // Set i and j according to direction 
            if (i < 0 && j <= n - 1) 
                i = 0; 
            if (j == n) 
                i = i + 2, j--; 
        } 
  
        // If Upward = 0 then traverse up to down 
        else { 
            for (; j >= 0 && i < n; i++, j--) { 
                cout << mat[i][j] << " "; 
                k++; 
            } 
  
            // Set i and j according to direction 
            if (j < 0 && i <= n - 1) 
                j = 0; 
            if (i == n) 
                j = j + 2, i--; 
        } 
  
        // change the direction by reverting upward
        Upward = !Upward; 
    } 
} `

**Comment by KevinKurian7** [comment]
`
  
void MatrixDiagonally(int mat[][100], int n) 
{ 
    // Initialize indexes to print the next element
    int i = 0, j = 0; 
  
    //initially the direction is from down to up
    bool Upward = true; 
  
    
    for (int k = 0; k < n * n;) { 
        // If Upward = true then traverse from downward 
        // to upward 
        if (Upward) { 
            for (; i >= 0 && j < n; j++, i--) { 
                cout << mat[i][j] << " "; 
                k++; 
            } 
  
            // Set i and j according to direction 
            if (i < 0 && j <= n - 1) 
                i = 0; 
            if (j == n) 
                i = i + 2, j--; 
        } 
  
        // If Upward = 0 then traverse up to down 
        else { 
            for (; j >= 0 && i < n; i++, j--) { 
                cout << mat[i][j] << " "; 
                k++; 
            } 
  
            // Set i and j according to direction 
            if (j < 0 && i <= n - 1) 
                j = 0; 
            if (i == n) 
                j = j + 2, i--; 
        } 
  
        // change the direction by reverting upward
        Upward = !Upward; 
    } 
} 
`
