### ISSUE TITLE
06 String --> 05 Implement strstr

### ISSUE THREAD

**Issue by FazeelUsmani** [FazeelUsmani/Amazon-SDE-Test-Series#54]
5. Implement strstr 
Basic Accuracy: 50.08% Submissions: 50457 Points: 1
Your task is to implement the function strstr. The function takes two strings as arguments (s,x) and  locates the occurrence of the string x in the string s. The function returns and integer denoting the first occurrence of the string x in s (0 based indexing).

 

Example 1:

Input:
s = GeeksForGeeks, x = Fr
Output: -1
Explanation: Fr is not present in the
string GeeksForGeeks as substring.
 

Example 2:

Input:
s = GeeksForGeeks, x = For
Output: 5
Explanation: For is present as substring
in GeeksForGeeks from index 5 (0 based
indexing).
 

Your Task:
You don't have to take any input. Just complete the strstr() function which takes two strings str, target as an input parameter. The function returns -1 if no match if found else it returns an integer denoting the first occurrence of the x in the string s.

 

Expected Time Complexity: O(|s|*|x|)
Expected Auxiliary Space: O(1)

Note : Try to solve the question in constant space complexity.

 

Constraints:
1 <= |s|,|x| <= 1000

**Comment by nixhantb** [comment]
Take the reference from here


public class Strstr {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		String s = "geeksforgeeks";
		String x = "for";
		int n = x.length();
		
		for(int i=0;i<s.length();i++) {
			if(s.substring(i,i+n).equals(x))
			System.out.println("Present");
			
			
			
			
		}
	}

}

**Comment by FazeelUsmani** [comment]
Hi @Nix-code, you can submit your pull request, I'll review and let you know

**Comment by FazeelUsmani** [comment]
You can find a git resource here: [https://learngitbranching.js.org/](https://learngitbranching.js.org/)
