### ISSUE TITLE
Please add question related to Bit manipulations

### ISSUE THREAD

**Issue by shreyshreyansh** [FazeelUsmani/Amazon-SDE-Test-Series#79]

**Comment by FazeelUsmani** [comment]
Sure. I'll add, till then you can have a look at [this repo](https://github.com/FazeelUsmani/Scaler-Academy/tree/master/006%20Bit%20Manipulation). And also there are very limited problems that can be done wholly using bit manipulation. Most of the time, you implement bit manipulation techniques to solve a bigger problem.
